version: "3"

services:
  vote:
    image: @@DHID@@/voting-vote
    command: python app.py
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
      image: @@DHID@@/voting-worker

  db:
    image: postgres:9.4

  result:
    image: @@DHID@@/voting-result
    command: nodemon --debug server.js
    ports:
      - "5001:80"
      - "5858:5858"
